name: RUN UNIT TEST

on:
  push:
    branches: [ testing ]
  pull_request:
    branches: [ testing ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run all unit tests
        run: mvn test

      - name: Run ImageOrderSaveTest
        run: mvn -Dtest=ImageOrderSaveTest test

      - name: Run ImageOrderPropertiesTest
        run: mvn -Dtest=ImageOrderPropertiesTest test

      - name: Run ImageContextTest
        run: mvn -Dtest=ImageContextTest test

      - name: Run OrderToStringTest
        run: mvn -Dtest=OrderToStringTest test

      - name: Run OrderButtonInteractionTest
        run: mvn -Dtest=OrderButtonInteractionTest test
